# Basic Python

## 1. Split this string

In [1]:
txt = "Hi there Sam!"

In [2]:
s =txt.split()

In [3]:
print(s)

['Hi', 'there', 'Sam!']

*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [4]:
planet = "Earth"
diameter = 12742

In [5]:
print("The diameter of {} is {} kilometers.".format(planet,diameter))

The diameter of Earth is 12742 kilometers.

## 3. In this nest dictionary grab the word "hello"

In [39]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,4,'hello']}]}]}

In [40]:
d['k1'][3]['tricky'][3]['target'][3]

4

# Numpy

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [8]:
import numpy  as np

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [11]:
print(np.arange(20,36,2))

[20 22 24 26 28 30 32 34]

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [13]:
a = np.array([1, 2, 3])

In [36]:
b = np.array([4, 6])

In [37]:

arr = np.concatenate((a,b))

In [38]:

print(arr)

[1 2 3 4 6]

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [17]:
import pandas as pd

In [18]:
data = {'name1':['r0', 'r1', 'r2', 'r3'],
        'name2':[20, 21, 19, 18]}

In [19]:
df = pd.DataFrame(data)

In [20]:
print(df)

  name1  name2
0    r0     20
1    r1     21
2    r2     19
3    r3     18

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [21]:
import numpy as np

In [22]:
import pandas as pd

In [32]:
df = pd.DataFrame(np.random.random((200,5)))

In [33]:
df['date'] = pd.date_range('2023-1-1', periods=200, freq='D')

In [34]:
df = df.set_index(['date'])

In [35]:
print(df.loc['2023-1-1':'2023-2-10'])

                   0         1         2         3         4
date
2023-01-01  0.174721  0.068912  0.386271  0.238320  0.038163
2023-01-02  0.950174  0.403716  0.591462  0.647769  0.231753
2023-01-03  0.291625  0.209403  0.819327  0.434076  0.560195
2023-01-04  0.244000  0.767395  0.900958  0.255388  0.594628
2023-01-05  0.491661  0.132217  0.249410  0.835261  0.835208
2023-01-06  0.495190  0.403340  0.757712  0.008412  0.722057
2023-01-07  0.142402  0.289850  0.516589  0.670080  0.383451
2023-01-08  0.348977  0.994884  0.936324  0.257194  0.661393
2023-01-09  0.699739  0.556381  0.176324  0.447756  0.510231
2023-01-10  0.079560  0.032367  0.013534  0.032287  0.482418
2023-01-11  0.118044  0.852413  0.310110  0.744354  0.087972
2023-01-12  0.375279  0.465151  0.377948  0.575178  0.076728
2023-01-13  0.236426  0.967808  0.937884  0.961313  0.910305
2023-01-14  0.377587  0.690800  0.707868  0.791499  0.525750
2023-01-15  0.960331  0.670864  0.963402  0.423965  0.068153
2023-01-16  0.749200  0.751377  0.968571  0.685353  0.537942
2023-01-17  0.144285  0.618281  0.230962  0.809835  0.596242
2023-01-18  0.514039  0.202682  0.850325  0.834795  0.250808
2023-01-19  0.502796  0.193545  0.184316  0.947010  0.420595
2023-01-20  0.132905  0.051928  0.950068  0.225370  0.290623
2023-01-21  0.433398  0.684055  0.854265  0.204112  0.660899
2023-01-22  0.797474  0.105591  0.033759  0.892624  0.143026
2023-01-23  0.313401  0.477302  0.550009  0.758816  0.839958
2023-01-24  0.314752  0.938190  0.723296  0.454348  0.665750
2023-01-25  0.117213  0.475481  0.807610  0.962096  0.173837
2023-01-26  0.589886  0.620230  0.231568  0.836970  0.083339
2023-01-27  0.318778  0.829579  0.642208  0.552632  0.389010
2023-01-28  0.892773  0.666696  0.250334  0.040485  0.684148
2023-01-29  0.626731  0.059448  0.656181  0.300964  0.272954
2023-01-30  0.768316  0.571567  0.747972  0.129139  0.051651
2023-01-31  0.668743  0.567921  0.533050  0.638858  0.135412
2023-02-01  0.085988  0.807229  0.876443  0.220612  0.296823
2023-02-02  0.083023  0.160497  0.914026  0.774721  0.978213
2023-02-03  0.369748  0.221427  0.972749  0.070498  0.227249
2023-02-04  0.733770  0.042638  0.306792  0.689959  0.070481
2023-02-05  0.691208  0.660095  0.145258  0.736134  0.947596
2023-02-06  0.585016  0.974111  0.077494  0.222715  0.166453
2023-02-07  0.501237  0.708067  0.970352  0.133580  0.084070
2023-02-08  0.795115  0.273363  0.330854  0.136576  0.034351
2023-02-09  0.556082  0.298744  0.873825  0.043828  0.576654
2023-02-10  0.521577  0.247941  0.115296  0.738280  0.875842

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [27]:
import pandas as pd

In [28]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [29]:
df = pd.DataFrame(lists, columns = ['col_0', 'col_1','col_2'])

In [30]:
print(df)

   col_0 col_1  col_2
0      1   aaa     22
1      2   bbb     25
2      3   ccc     24